### PR TITLE
Fvk sqlfluff pluto

### PR DESCRIPTION
**Pull request by fvankrieken**
Ended up adding a regex to our py toml for templating to support psql variables in the formats `:VAR`, `:'VAR'`, and `:"VAR"`, since [there is not a style that supports these implemented](https://github.com/sqlfluff/sqlfluff/blob/d8a1be87c7b21e7f8e8d7624a7c62bb5a9825963/src/sqlfluff/core/templaters/placeholder.py#L23)

I've opened a ticket in sqlfluff: https://github.com/sqlfluff/sqlfluff/issues/5140
and implemented a fix in [my own fork](https://github.com/fvankrieken/sqlfluff/commit/c66b841d0c6bca7016487aab9e157455c05fc7fc) to add this as an accepted templater format. For now, implemented via fix in our pyproject.toml

In this PR, the only other changes are a few variable renamings in bash/sql just to make it a bit more clear/consistent what's being done

### CODE REVIEW

**Comment by fvankrieken** [comment]
Running build right now to make sure nothing broken by fluffing

**Comment by fvankrieken** [comment]
Fluffing in tests takes a bit over 1 minute, so not a real need to limit to changed files (@damonmcc chatted about this being a potential issue briefly)

**Review by alexrichey — APPROVED** [review]
Potentially getting an open source (well, non-DCP open source) contribution out of this is super cool. Nicely done!

**Comment by fvankrieken** [comment]
QA'd outputs, looks good

**Pull request merged**
