### PR TITLE
add optional left_columns arg

### PR DESCRIPTION
**Pull request by fvankrieken**
To specify columns, can do so like

```sql
WITH a AS (
    ...
),
clipped_to_nyc AS (
    {{ clip_to_geom(left=a, left_by="wkb_geometry", left_columns=["variable_type", "variable_id"]) }}
)
SELECT * FROM clipped_to_nyc
```

### CODE REVIEW

**Comment by sf-dcp** [comment]
nice! Have you given it a try?

**Comment by fvankrieken** [comment]
I did use it.

Nothing from the right table is selected, and that's why there's the `{{ dbt_utils.star(from=left, except=[left_by]) }}` when no columns are supplied, so that the left geom column is not selected/duplicated

**Comment by fvankrieken** [comment]
You know, I _compiled_ a model using it, not ran. Let me run it with a CTE

**Comment by sf-dcp** [comment]
> I did use it.
> 
> Nothing from the right table is selected, and that's why there's the `{{ dbt_utils.star(from=left, except=[left_by]) }}` when no columns are supplied, so that the left geom column is not selected/duplicated

Got it.  In the second part of the logic below, it seems like we will be selecting `left_by` column, no?

```jinja
        {% else %}
            {% for column in left_columns %}
                left.{{ column }},
            {% endfor %}
```

**Comment by fvankrieken** [comment]
That's iterating through the argument explicitly provided for selecting by the user, so I'm just going to trust people to select what they need in that case

**Review by sf-dcp — APPROVED** [review]
Thanks for taking a stab at it!

**Comment by fvankrieken** [comment]
Caught a little bug, works now

**Comment by sf-dcp** [comment]
@fvankrieken, I tried to use the macro in my code like this and I'm getting a syntax error: 

```sql

WITH reprojected AS ( ...
),

clipped_to_nyc AS (
    {{ clip_to_geom(left=reprojected, left_by="geom", left_columns=["objectid"]) }}
),

```

Here is the compiled query:

```sql 
reprojected AS (...
),

clipped_to_nyc AS (
    SELECT
         .objectid,
         ST_INTERSECTION(.raw_geom, "db-green-fast-track"."sf_gft_shadows"."stg__nyc_boundary".geom) AS geom
    FROM 
    INNER JOIN "db-green-fast-track"."sf_gft_shadows"."stg__nyc_boundary" 
    ON ST_INTERSECTS(.raw_geom, "db-green-fast-track"."sf_gft_shadows"."stg__nyc_boundary".geom)


),
```

So the compiled query doesn't know the CTE name. Do you know what I'm doing wrong? You said it worked on your CTE

**Comment by sf-dcp** [comment]
Nevermind, solved the issue! The CTE name should be in quotes when calling the macro

**Pull request merged**
