### PR TITLE
Compile python requirements

### PR DESCRIPTION
**Pull request by fvankrieken**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by fvankrieken** [comment]
There was a new version of py-arrow stubs - maintainer aligned versioning with pyarrow. So seeing if just updating it fixes our issue in #1102

**Comment by fvankrieken** [comment]
Submitted a PR to `pyarrow-stubs` 

https://github.com/zen-xu/pyarrow-stubs/pull/67

**Comment by damonmcc** [comment]
other than PLUTO and ZTL failing, I think the only fail now is a (different) `mypy` issue [here](https://github.com/NYCPlanning/data-engineering/actions/runs/10714333292/job/29708019496?pr=1105):

```bash
dcpy/utils/geospatial/parquet.py:16: error: Unsupported right operand type for in ("dict[bytes, bytes] | None")  [operator]
dcpy/utils/geospatial/parquet.py:18: error: Value of type "dict[bytes, bytes] | None" is not indexable  [index]
dcpy/utils/geospatial/parquet.py:30: error: Unsupported right operand type for in ("dict[bytes, bytes] | None")  [operator]
```

**Comment by fvankrieken** [comment]
Seem like actual changes (one field of class becoming optional). I'll fix

**Pull request merged**
