### PR TITLE
DevDB - 2020 Census Incorporation

### LINKED ISSUE #28: Enhancements for 23Q2 release
Porting of https://github.com/NYCPlanning/db-developments/issues/644

Housing team requested enhancements for July release.  Request made on May 1.  This may be a running list / will need to finalize list before starting work.

- [x] archive census with data library
---> 2020 Census Data is available [here](https://www.nyc.gov/site/planning/planning-level/nyc-population/2020-census.page) for census blocks, or census tracts and higher

Aggregate tables
- [x] Add 2020 unit count from the Census. 
- [x] Add a comp2020ap column to be used with the 2020 Census unit count. From 2020 census, use the "HUnits" field under 2020 Census Data for blocks, and "HUnits_20" field for census tracts and higher.  The data will basically replace the 2010 data we have.
- [x] Drop the comp2010ap column since we are no longer using the 2010 baseline.

Main table
- [x] Drop all of the 2010 geography columns

Tangentially related to #21

### PR DESCRIPTION
**Pull request by fvankrieken**
Closes #28 

A couple things going on here, as outlined in #28 

- drop 2010 geometries
  - dataloading/import
  - as columns in tables during build/export
- import 2020 census data (recently added in data library)
- create "cleaned" table that has census housing units by each geography
- join these into the spatial aggregate unit summary tables

Latest build here
https://github.com/NYCPlanning/data-engineering/actions/runs/5393678702

### CODE REVIEW

**Comment by damonmcc** [comment]
@fvankrieken
are there any build runs using these changes? mostly to see if they're breaking changes

**Comment by fvankrieken** [comment]
> @fvankrieken are there any build runs using these changes? mostly to see if they're breaking changes

Just updated description

**Comment by fvankrieken** [comment]
Getting gdal warnings for shapefile export
 > Warning 1: Value 178967569.63499999 of field shape_area of feature 22 not successfully written. Possibly due to too larger number with respect to field width
Going to look into how this manifests (rounding/truncation? Or just doesn't write at all)

**Review by damonmcc — APPROVED** [review]
lgtm!

**Comment by fvankrieken** [comment]
Seem to be exporting just fine as far as I can tell. I've found people complaining about this warning

https://trac.osgeo.org/gdal/ticket/6803

**Comment by fvankrieken** [comment]
Slightly more recent ticket https://github.com/OSGeo/gdal/issues/3709

**Pull request merged**
