### PR TITLE
Compile python requirements

### PR DESCRIPTION
**Pull request by fvankrieken**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by fvankrieken** [comment]
Breaking change from numpy 2.0.0!

https://github.com/NYCPlanning/data-engineering/actions/runs/9627004556/job/26553697935#step:6:870

It is based on string representation of an error message that we generate. Seems that using a [dict within a format string](https://github.com/NYCPlanning/data-engineering/blob/2da856b403b1782a28f1d023ad3ae50fb3a9c030/dcpy/lifecycle/package/validate.py#L211) now specifies type

**Comment by alexrichey** [comment]
@fvankrieken We should probably just cast to the python `int` in the failing case. Happy to make that change, if you're not already on it

**Comment by damonmcc** [comment]
would love to upgrade as well

**Comment by fvankrieken** [comment]
> @fvankrieken We should probably just cast to the python `int` in the failing case. Happy to make that change, if you're not already on it.
> 
> All for upgrading, otherwise.

All yours 🙂

**Comment by alexrichey** [comment]
Fix [here](https://github.com/NYCPlanning/data-engineering/pull/948) (created a new branch/PR so it wouldn't be overwritten)

**Pull request closed without merging**
