### PR TITLE
Compile python requirements

### PR DESCRIPTION
**Pull request by fvankrieken**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

Changes: unpin geopandas & black for latest version.

Nightly build [here](https://github.com/NYCPlanning/data-engineering/actions/runs/8806040049)

### CODE REVIEW

**Comment by fvankrieken** [comment]
Do you want to aim this at main?

**Comment by damonmcc** [comment]
@fvankrieken I think the reason to aim this PR at the dev branch is to then merge both the manual unpinning commit and the auto-compile commit to `main`

**Review by damonmcc — APPROVED** [review]

**Comment by fvankrieken** [comment]
Gotcha. In that case, you should feel free to merge without approval!

**Comment by sf-dcp** [comment]
I got confused having these 2 PRs lol. @damonmcc, thanks for clarifying!

**Pull request merged**
