### PR TITLE
Add diagram of our build workflow

### PR DESCRIPTION
**Pull request by damonmcc**
this diagram is an attempt to describe the highest-level steps we usually/want to take when we build products

I don't think it's 100% accurate for every product nor is it the workflow we want forever

I used the terms "fresh" and "stale" to relate to "is source data up to date" as inspired by [dbt](https://docs.getdbt.com/docs/deploy/source-freshness). but if there's better terms to use that work in a small diagram, happy to try em

[here](https://github.com/NYCPlanning/data-engineering/wiki/Operations#building-data-products) is how it looks embedded in our wiki

### CODE REVIEW

**Review by alexrichey — DISMISSED** [review]
Nice. Were you also checking in diagram source files for this as well?

**Comment by damonmcc** [comment]
> Nice. Were you also checking in diagram source files for this as well?

oh sorry I should've noted, `FILENAME.drawio.png` is both a source and image file!

@TangoYankee mentioned yesterday that a `FILENAME.drawio.svg` would be editable in the VS code drawio extension, but it didn't seem to render in github so i tried png

**Review by fvankrieken — APPROVED** [review]

**Comment by TangoYankee** [comment]
> > Nice. Were you also checking in diagram source files for this as well?
> 
> oh sorry I should've noted, `FILENAME.drawio.png` is both a source and image file!
> 
> @TangoYankee mentioned yesterday that a `FILENAME.drawio.svg` would be editable in the VS code drawio extension, but it didn't seem to render in github so i tried png
> 
> maybe we can convert the other diagrams to this approach too

Hello! Inspired by DE, I've experimented with drawio. Under my personal account, I have an example of how I have been using the drawio.svg filetype. Here it is in a [folder readme](https://github.com/TangoYankee/purple-hawk/tree/main/diagram), opened [on github](https://github.com/TangoYankee/purple-hawk/blob/main/diagram/db.drawio.svg) and opened in [its own browser tab](https://raw.githubusercontent.com/TangoYankee/purple-hawk/1704dd4c249fc6d99bcd3c380fccbce7135b51fd/diagram/db.drawio.svg). I'm not sure why it would fail to render within the DE repo.

Please ignore the actual content of the file- it's not ready for DE scrutiny.

**Comment by sf-dcp** [comment]
It looks great! Though I have a question: do we want to add/modify a step to mention opening a build GH issue? The last step indicates closing an issue.

**Comment by damonmcc** [comment]
> It looks great! Though I have a question: do we want to add/modify a step to mention opening a build GH issue? The last step indicates closing an issue.

will fix!

**Pull request merged**
