### PR TITLE
github action for single freeform command

### PR DESCRIPTION
**Pull request by fvankrieken**
Any concerns with something like this? Seems useful for dev tasks that have performance constraints

### CODE REVIEW

**Review by damonmcc — APPROVED** [review]
seems useful! I imagine needing more secret envars for some commands, but those can always be added later

**Comment by alexrichey** [comment]
@fvankrieken I think there are some potential concerns around security here. Since we're loading secrets into the container, anyone who can run this has full access to all creds

**Comment by fvankrieken** [comment]
Yeah, makes sense.

**Comment by alexrichey** [comment]
however, would this be useful without creds?

**Pull request closed without merging**
